### ISSUE TITLE
Hello, how to generate NPZ file?

### ISSUE THREAD

**Issue by hetiansheng123** [CVEO/OBIC-GCN#1]
Hello, excuse me, I want to change the data set, how to generate.npz file?  Thank you very much for your answer

**Comment by chenguanzhou** [comment]
1. The npz file is generated by the code in utils.py
2. The following data file is required: mask_path, features_path, training_data_path, validation_data_path, test_data_path.
The first two are the mask data of objectid (that is, the raster result of image segmentation) and the features of each object (generated in software that supports OBIC, such as ENVI, eCognition, CDTStudio, etc.). For the specific format, please refer to utils.py
